version: "3"

services:
  ccbp-ide:
    ipc: host
    restart: always
    image: nxtwave/ccbp-ide:latest
    container_name: ccbp-ide
    ports:
      - "80:80"
      - "8000:8000"
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "5000:5000"
      - "5500:5500"
    volumes:
      - "./.workspace/:/home/workspace/"
